name: Github Pages
on: [push]
jobs:
  Build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.3.0
        with:
          hugo-version: "0.68.3"

      - name: Build
        run: hugo --minify -e production

      - name: Upload deployment package
        uses: actions/upload-artifact@v1
        with:
          name: public
          path: public/

  Deploy:
    runs-on: ubuntu-18.04
    if: ${{ github.ref == 'refs/heads/master' }}
    needs:
      - "Build"
    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v1
        with:
          name: public

      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Upload algolia records
        run: npm run algolia
        env:
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          EXTERNAL_REPOSITORY: gghcode/gghcode.github.io
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
